steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/luribeiro:$COMMIT_SHA', '-f', 'LR/Dockerfile', '.' ]

  # Push para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/luribeiro:$COMMIT_SHA' ]

  # Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'luribeiro',
        '--image', 'gcr.io/$PROJECT_ID/luribeiro:$COMMIT_SHA',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/luribeiro:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
