# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  diskSizeGb: 50
  cache: true

steps:
  # 1️⃣ Build da imagem Docker com cache
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/luribeiro/luribeiro:$COMMIT_SHA',
        '--cache-from', 'us-central1-docker.pkg.dev/$PROJECT_ID/luribeiro/luribeiro:latest',
        '-f', 'LR/Dockerfile',
        'LR'
      ]
    env:
      - 'DOCKER_BUILDKIT=1'

  # 2️⃣ Push para Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/luribeiro/luribeiro:$COMMIT_SHA'
      ]

  # 3️⃣ Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'luribeiro',
        '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/luribeiro/luribeiro:$COMMIT_SHA',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/luribeiro/luribeiro:$COMMIT_SHA'
