# cloudbuild.yaml (COLE na RAIZ do repo: LucimaraRibeiro/cloudbuild.yaml)
substitutions:
  _SERVICE: "luribeiro"      # nome do serviço Cloud Run (troque se quiser)
  _REGION: "us-central1"    # sua região (ajuste se preferir)

steps:
# build com Dockerfile explícito e contexto LR
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA',
      '-f', 'LR/Dockerfile',
      'LR'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy ${_SERVICE} \
        --image gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA \
        --region ${_REGION} \
        --platform managed \
        --allow-unauthenticated

images:
- 'gcr.io/$PROJECT_ID/${_SERVICE}:$COMMIT_SHA'
#
